# Generated by Django 4.2.4 on 2023-08-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "fileID",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="fileID"
                    ),
                ),
                ("filename", models.CharField(max_length=25, verbose_name="filename")),
                ("pid", models.IntegerField(verbose_name="pid")),
                ("father", models.IntegerField(verbose_name="father")),
                ("depth", models.IntegerField(verbose_name="depth")),
                ("type", models.IntegerField(verbose_name="type")),
                ("docID", models.IntegerField(null=True, verbose_name="docID")),
            ],
        ),
    ]
