# Generated by Django 4.2.4 on 2023-08-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doc",
            fields=[
                (
                    "docId",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="docId"
                    ),
                ),
                ("pid", models.IntegerField(verbose_name="pid")),
                ("docname", models.CharField(max_length=25, verbose_name="docname")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is_active"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocContent",
            fields=[
                (
                    "docContentId",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="docContentId"
                    ),
                ),
                ("docId", models.IntegerField(verbose_name="docId")),
                ("docContent", models.TextField(default="", verbose_name="docContent")),
                (
                    "saveTime",
                    models.DateTimeField(auto_now_add=True, verbose_name="saveTime"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is_active"),
                ),
            ],
        ),
    ]
