# Generated by Django 4.1.2 on 2023-08-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Doc", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("groupid", models.CharField(max_length=55, verbose_name="groupid")),
                ("authorid", models.CharField(max_length=55, verbose_name="authorid")),
                (
                    "sessionid",
                    models.CharField(max_length=55, verbose_name="sessionid"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="doc",
            name="padid",
            field=models.CharField(default=0, max_length=55, verbose_name="padid"),
            preserve_default=False,
        ),
    ]
