# Generated by Django 4.2.4 on 2023-09-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "tid",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="tid"
                    ),
                ),
                ("teamname", models.CharField(max_length=25, verbose_name="teamname")),
                (
                    "teaminform",
                    models.TextField(max_length=255, verbose_name="teaminform"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is_active"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User_team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.IntegerField(verbose_name="uid")),
                ("tid", models.IntegerField(verbose_name="tid")),
                ("status", models.CharField(max_length=25, verbose_name="status")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is_active"),
                ),
            ],
        ),
    ]
