# Generated by Django 4.1.2 on 2023-08-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Team", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_team",
            name="tid",
            field=models.IntegerField(max_length=25, verbose_name="tid"),
        ),
        migrations.AlterField(
            model_name="user_team",
            name="uid",
            field=models.IntegerField(max_length=25, verbose_name="uid"),
        ),
    ]
