# Generated by Django 4.1.2 on 2023-08-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Team", "0002_alter_user_team_tid_alter_user_team_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_team",
            name="tid",
            field=models.IntegerField(verbose_name="tid"),
        ),
        migrations.AlterField(
            model_name="user_team",
            name="uid",
            field=models.IntegerField(verbose_name="uid"),
        ),
    ]
