# Generated by Django 4.2.4 on 2023-08-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="record",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
