# Generated by Django 4.2.4 on 2023-08-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chat", "0002_record_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="type",
            field=models.CharField(default="chat", max_length=25, verbose_name="type"),
        ),
    ]
