# Generated by Django 4.1.2 on 2023-08-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chat", "0002_chatroom_is_active_record_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatuser",
            old_name="uid1",
            new_name="from_uid",
        ),
        migrations.RenameField(
            model_name="chatuser",
            old_name="uid2",
            new_name="to_uid",
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="cname",
            field=models.CharField(default="FusionChat", max_length=256),
        ),
    ]
