# Generated by Django 4.1.2 on 2023-08-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chat", "0003_rename_uid1_chatuser_from_uid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="tid",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="record",
            name="uid",
            field=models.IntegerField(null=True),
        ),
    ]
