# Generated by Django 4.2.4 on 2023-09-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "pid",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="pid"
                    ),
                ),
                (
                    "project_name",
                    models.CharField(max_length=25, verbose_name="project_name"),
                ),
                (
                    "project_inform",
                    models.TextField(max_length=255, verbose_name="project_inform"),
                ),
                ("tid", models.IntegerField(verbose_name="tid")),
                ("uid", models.IntegerField(verbose_name="uid")),
                ("groupid", models.CharField(max_length=55, verbose_name="groupid")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="create_time"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is_active"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Protoinfo",
            fields=[
                (
                    "proto_info_id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="proto_info_id"
                    ),
                ),
                ("info", models.JSONField(null=True, verbose_name="info")),
                ("useid", models.IntegerField(default=-1, verbose_name="useid")),
            ],
        ),
        migrations.CreateModel(
            name="Protomodel",
            fields=[
                (
                    "modelid",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="modelid"
                    ),
                ),
                ("modelinfo", models.JSONField(null=True, verbose_name="modelinfo")),
            ],
        ),
        migrations.CreateModel(
            name="Prototype",
            fields=[
                (
                    "protoid",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="protoid"
                    ),
                ),
                ("pid", models.IntegerField(verbose_name="pid")),
                (
                    "protoname",
                    models.CharField(max_length=25, verbose_name="protoname"),
                ),
            ],
        ),
    ]
