# Generated by Django 4.2.4 on 2023-08-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "pid",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="pid"
                    ),
                ),
                (
                    "project_name",
                    models.CharField(max_length=25, verbose_name="project_name"),
                ),
                (
                    "project_inform",
                    models.TextField(max_length=255, verbose_name="project_inform"),
                ),
                ("tid", models.IntegerField(verbose_name="tid")),
                ("uid", models.IntegerField(verbose_name="uid")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is_active"),
                ),
            ],
        ),
    ]
