# Generated by Django 4.1.2 on 2023-08-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="groupid",
            field=models.CharField(default=0, max_length=55, verbose_name="groupid"),
            preserve_default=False,
        ),
    ]
