# Generated by Django 4.2.4 on 2023-08-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="create_time",
            field=models.DateTimeField(null=True, verbose_name="create_time"),
        ),
    ]
