# Generated by Django 4.2.4 on 2023-08-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0002_prototype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Protoinfo",
            fields=[
                (
                    "proto_info_id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="proto_info_id"
                    ),
                ),
                ("info", models.JSONField(verbose_name="info")),
            ],
        ),
        migrations.RemoveField(
            model_name="prototype",
            name="info",
        ),
    ]
