# Generated by Django 4.2.4 on 2023-08-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0002_project_groupid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="create_time",
            field=models.DateTimeField(
                auto_now_add=True, default=0, verbose_name="create_time"
            ),
            preserve_default=False,
        ),
    ]
