# Generated by Django 4.2.4 on 2023-08-31 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0003_alter_project_create_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="protoinfo",
            name="use",
            field=models.BooleanField(default=False, verbose_name="use"),
        ),
    ]
