# Generated by Django 4.2.4 on 2023-08-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0004_protoinfo_use"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="protoinfo",
            name="use",
        ),
        migrations.AddField(
            model_name="protoinfo",
            name="useid",
            field=models.IntegerField(null=True, verbose_name="useid"),
        ),
    ]
