# Generated by Django 4.2.4 on 2023-08-31 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0006_alter_protoinfo_useid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protoinfo",
            name="info",
            field=models.JSONField(null=True, verbose_name="info"),
        ),
    ]
