# Generated by Django 4.2.4 on 2023-09-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0007_alter_protoinfo_info"),
    ]

    operations = [
        migrations.CreateModel(
            name="Protomodel",
            fields=[
                (
                    "modelid",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="modelid"
                    ),
                ),
                ("modelinfo", models.JSONField(null=True, verbose_name="modelinfo")),
            ],
        ),
    ]
