# Generated by Django 4.2.4 on 2023-08-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Captcha",
            fields=[
                (
                    "email",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="email",
                    ),
                ),
                ("captcha", models.CharField(max_length=10, verbose_name="captcha")),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "uid",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="uid"
                    ),
                ),
                ("username", models.CharField(max_length=25, verbose_name="username")),
                ("password", models.CharField(max_length=25, verbose_name="password")),
                ("name", models.CharField(max_length=10, verbose_name="name")),
                (
                    "phone",
                    models.CharField(
                        default="null", max_length=11, verbose_name="phone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="null", max_length=254, verbose_name="email"
                    ),
                ),
                ("avatar", models.TextField(null=True, verbose_name="avatar")),
                ("identity", models.IntegerField(default=0, verbose_name="identity")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is_active"),
                ),
            ],
        ),
    ]
