# Generated by Django 4.2.4 on 2023-08-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="captcha",
            name="email",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, verbose_name="email"
            ),
        ),
    ]
