# Generated by Django 4.2.4 on 2023-09-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0003_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="logincnt",
            field=models.IntegerField(default=0, verbose_name="logincnt"),
        ),
    ]
