# Generated by Django 4.2.4 on 2023-09-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0005_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.CharField(
                default="http://rzyi06q9n.hb-bkt.clouddn.com/lufei.jpg",
                max_length=255,
                verbose_name="avatar",
            ),
        ),
    ]
